[Config General]
image-path=../images

network = Network

sim-time-limit 		= 300s
seed-0-mt           = 1

output-scalar-file  = results/General/General.sca
output-vector-file  = results/General/General.vec
eventlog-file = results/event.elog
snapshot-file = results/snapshot.sna


# Configurator settings
*.configurator.dumpAddresses = true
*.configurator.dumpTopology = true
*.configurator.dumpLinks = true
*.configurator.dumpRoutes = true
*.configurator.config = xmldoc("config.xml")

# Visualizer settings
*.visualizer.interfaceTableVisualizer.displayInterfaceTables = false
*.visualizer.interfaceTableVisualizer.nodeFilter = "gnb* or apple_device_host or server or upf or iUpf or apple_device_host[*] or ualcmp or airtag"

# Link settings
*.cableBandwidth = 100Mbps
*.cableLength = 2km
*.closeCableBandwidth = 100Mbps
*.closeCableLength = 1km

*.cableBandwidth.param-record-as-scalar = true
*.cableLength.param-record-as-scalar = true

# Routing settings
*.*.ipv4.arp.typename = "GlobalArp"
*.*.ipv4.routingTable.netmaskRoutes = ""

# Router settings
*.*router.ppp[*].queue.typename = "DropTailQueue"
*.*router.ppp[*].queue.packetCapacity = 40

*.*upf.ppp[*].queue.typename = "DropTailQueue"
*.*upf.ppp[*].queue.packetCapacity = 40

*.server.numApps = 1
*.server.app[0].typename = "ServerApp"
*.server.app[0].startTime  = uniform(0s, 1s)


*.apple_host_number.param-record-as-scalar = true
*.airtag_number.param-record-as-scalar = true
#*.airtag[1].app[0].destAddress = "apple_device_host[]"
# -----------------------------------------------------------------
*.apple_device_host[*].numApps = 1
*.apple_device_host[*].app[0].destAddress = "server"
*.apple_device_host[*].app[0].sendInterval = int(uniform(6s, 12s))
*.apple_device_host[*].app[0].startTime  = uniform(1s, 2s)
*.apple_device_host[*].app[0].typename = "ClientApp"


# -----------------------------------------------------------------
*.airtag[*].numApps = 1
*.airtag[*].app[0].typename = "SendLocationApp"
#*.airtag[*].app[0].destAddress = "apple_device_host[" + string(parentIndex()) +"]"
*.airtag[*].app[0].destPort = 5555
*.airtag[*].app[0].sendInterval = int(uniform(5s, 10s))
*.airtag[*].app[*].startTime = 5s
#----------------------------------------------------------------------------------------------------------------
**.downlink_interference = true
**.uplink_interference = true
**.ueTxPower = 26
**.eNodeBTxPower = 46
**.targetBler = 0.01
**.blerShift = 5  
**.fbPeriod = 120   # reports CQI every 120ms

**.sctp.nagleEnabled = false
**.sctp.enableHeartbeats = false

**.mac.schedulingDisciplineDl = "MAXCI" 
**.mac.schedulingDisciplineUl = "MAXCI"

**.dynamicCellAssociation = true

*.carrierAggregation.numComponentCarriers = 1
*.carrierAggregation.componentCarrier[0].numerologyIndex = ${u=0}
*.carrierAggregation.componentCarrier[0].carrierFrequency = 2GHz
*.carrierAggregation.componentCarrier[0].numBands = ${numRbs=50}

*.gnb*.cellularNic.numCarriers = 1
*.gnb*.cellularNic.channelModel[0].componentCarrierIndex = 0
*.apple_device_host[*].cellularNic.numCarriers = 1
*.apple_device_host[*].cellularNic.nrChannelModel[0].componentCarrierIndex = 0
#----------------------------------------------------------------------------------------------------------------
*.gnb*.mobility.initFromDisplayString = false
*.gnb*.mobility.initialZ = 0m


*.gnb1.mobility.initialX = 1110m
*.gnb1.mobility.initialY = 2000m

*.gnb2.mobility.initialX = 3830m
*.gnb2.mobility.initialY = 2000m

*.gnb3.mobility.initialX = 2500m
*.gnb3.mobility.initialY = 4500m
############### X2 configuration #################
*.gnb*.numX2Apps = 2                                        # one x2App per peering node
*.gnb*.x2App[*].server.localPort = 5000 + ancestorIndex(1)  # Server ports (x2App[0]=5000, x2App[1]=5001, ...)
*.gnb1.x2App[0].client.connectAddress = "gnb2%x2ppp0" 
*.gnb1.x2App[1].client.connectAddress = "gnb3%x2ppp0"
*.gnb2.x2App[0].client.connectAddress = "gnb1%x2ppp0" 
*.gnb2.x2App[1].client.connectAddress = "gnb3%x2ppp1"
*.gnb3.x2App[0].client.connectAddress = "gnb1%x2ppp1" 
*.gnb3.x2App[1].client.connectAddress = "gnb2%x2ppp1"
#----------------------------------------------------------------------------------------------------------------
*.apple_device_host[*].macCellId = 0
*.apple_device_host[*].masterId = 0
*.apple_device_host[*].nrMacCellId = 1
*.apple_device_host[*].nrMasterId = 1


#----------------------------------------------------------------------------------------------------------------

############ UEs position #################
*.apple_device_host[*].mobility.typename = "CircleMobility"
*.apple_device_host[*].mobility.cx = 2500m
*.apple_device_host[*].mobility.cy = 2500m
*.apple_device_host[*].mobility.r = uniform(250m, 2500m)
#*.apple_device_host[1].mobility.r = 550m
*.apple_device_host[*].mobility.speed = uniform(-70mps, 70mps)
*.apple_device_host[*].mobility.startAngle = uniform(0deg, 360deg)


*.airtag[*].mobility.typename = "CircleMobility"
*.airtag[*].mobility.cx = 2500m
*.airtag[*].mobility.cy = 2500m
*.airtag[*].mobility.r = uniform(250m, 2500m)
*.airtag[*].mobility.speed = uniform(-70mps, 70mps)
*.airtag[*].mobility.startAngle = uniform(0deg, 360deg)


*.apple_host_number = ${genconfig1num=int(uniform(25, 25))}
*.airtag_number = ${genconfigairtag1num=int(uniform(15, 15))}
*.apple_device_host[*].app[0].airtag_number = ${genconfigairtag1num}
*.apple_device_host[*].app[0].apple_host_number = ${genconfig1num}
*.apple_device_host[*].app[0].friendly_iphones_num = int(uniform(1, 6))
*.apple_device_host[*].app[0].friendly_airtags_num = int(uniform(1, 6))

#----------------------------------------------------------------------------------------------------------------
[Config lowDeviceAmount]
*.apple_host_number = ${config1num=int(uniform(13, 13))}
*.airtag_number = ${configairtag1num=int(uniform(6, 6))}
*.apple_device_host[*].app[0].airtag_number = ${configairtag1num}
*.apple_device_host[*].app[0].apple_host_number = ${config1num}
output-scalar-file  = results/lowDeviceAmount/lowDeviceAmount.sca
output-vector-file  = results/lowDeviceAmount/lowDeviceAmount.vec

[Config highDeviceAmount]
*.apple_host_number = ${config2num=int(uniform(40, 40))}
*.airtag_number = ${configairtag2num=int(uniform(25, 25))}
*.apple_device_host[*].app[0].airtag_number = ${configairtag2num}
*.apple_device_host[*].app[0].apple_host_number = ${config2num}
output-scalar-file  = results/highDeviceAmount/highDeviceAmount.sca
output-vector-file  = results/highDeviceAmount/highDeviceAmount.vec

[Config longCableLength]
*.cableLength = 3000km
output-scalar-file  = results/longCableLength/longCableLength.sca
output-vector-file  = results/longCableLength/longCableLength.vec
