//
// Generated file, do not edit! Created by opp_msgtool 6.1 from DataPacket.msg.
//

#ifndef __INET_DATAPACKET_M_H
#define __INET_DATAPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class DataPacket;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/common/L3AddressTag_m.h" // import inet.networklayer.common.L3AddressTag

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry


namespace inet {

/**
 * Class generated from <tt>DataPacket.msg:8</tt> by opp_msgtool.
 * <pre>
 * class DataPacket extends FieldsChunk
 * {
 *     // Type-0 = AirTag location
 *     // Type-1 = Airtag lookup request 
 *     // Type-2 = Airtag lookup response
 *     // Type-3 = Iphone location
 *     // Type-4 = Iphone lookup request
 *     // Type-5 = Iphone lookup response
 *     // Type-6 = Friendly Sharing Location 
 *     int type;
 *     string deviceName;
 *     L3Address ip;
 *     int isDeviceFound;
 *     Coord deviceLocation;
 *     string textMessage;
 * }
 * </pre>
 */
class DataPacket : public ::inet::FieldsChunk
{
  protected:
    int type = 0;
    ::omnetpp::opp_string deviceName;
    L3Address ip;
    int isDeviceFound = 0;
    Coord deviceLocation;
    ::omnetpp::opp_string textMessage;

  private:
    void copy(const DataPacket& other);

  protected:
    bool operator==(const DataPacket&) = delete;

  public:
    DataPacket();
    DataPacket(const DataPacket& other);
    virtual ~DataPacket();
    DataPacket& operator=(const DataPacket& other);
    virtual DataPacket *dup() const override {return new DataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getType() const;
    virtual void setType(int type);

    virtual const char * getDeviceName() const;
    virtual void setDeviceName(const char * deviceName);

    virtual const L3Address& getIp() const;
    virtual L3Address& getIpForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<DataPacket*>(this)->getIp());}
    virtual void setIp(const L3Address& ip);

    virtual int getIsDeviceFound() const;
    virtual void setIsDeviceFound(int isDeviceFound);

    virtual const Coord& getDeviceLocation() const;
    virtual Coord& getDeviceLocationForUpdate() { handleChange();return const_cast<Coord&>(const_cast<DataPacket*>(this)->getDeviceLocation());}
    virtual void setDeviceLocation(const Coord& deviceLocation);

    virtual const char * getTextMessage() const;
    virtual void setTextMessage(const char * textMessage);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataPacket& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::DataPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::DataPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_DATAPACKET_M_H

